# Obsidian Note Template

name: note-template 
parent: default

matches:
  - trigger: ":t"
    replace: "*Title:*
              *Card Address:*
              *Date:*
              *Tags:*
              
              ---
              ##### Notes

              ---
              ##### Extra Thoughts

              ---
              ##### New Questions

              ---
              **Related Notes**

              ---
              **Pictures**

              ---
              **Copy Pasta**

              ---
              **External Links**"
